### ISSUE TITLE
[BUG] Cannot build on Flutter 3.29.0 - Unresolved reference: Registrar

### ISSUE THREAD

**Issue by mateusz-bak** [Raincal/blurhash#22]
Hello! I'm unable to build/run app when using package `blurhash` on version 1.1.1 after upgrading Flutter to 3.29.0.
```
e: file:///home/user/.pub-cache/hosted/pub.dev/blurhash-1.1.1/android/src/main/kotlin/com/raincal/blurhash/BlurhashPlugin.kt:14:48 Unresolved reference: Registrar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':blurhash:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
Error: Gradle task assembleDebug failed with exit code 1
```

Commenting out the line
`import io.flutter.plugin.common.PluginRegistry.Registrar`
in 
`/home/user/.pub-cache/hosted/pub.dev/blurhash-1.1.1/android/src/main/kotlin/com/raincal/blurhash/BlurhashPlugin.kt`
Resolves the issue.

**Comment by Raincal** [comment]
fixed in version 1.2.0
